#!/bin/bash
# deployment-steps.sh - GitHub and Vercel Deployment Guide

echo "🚀 OpenClaw Setup Service - Deployment Steps"
echo "============================================="

echo ""
echo "📋 Step 1: Create GitHub Repository"
echo "1. Go to https://github.com/new"
echo "2. Repository name: 'openclaw-setup-service'"
echo "3. Make it Public"
echo "4. Add README.md, .gitignore, and license"
echo "5. Click 'Create repository'"
echo ""

echo "📋 Step 2: Connect GitHub with Git"
echo "Run these commands in your waitlist-pro directory:"
echo ""
echo "# Add GitHub as remote origin"
echo "git remote add origin https://github.com/YOUR_USERNAME/openclaw-setup-service.git"
echo ""
echo "# Push to GitHub"
echo "git branch -M main"
echo "git push -u origin main"
echo ""

echo "📋 Step 3: Deploy to Vercel"
echo "1. Go to https://vercel.com"
echo "2. Sign up/login with GitHub"
echo "3. Click 'New Project'"
echo "4. Import your 'openclaw-setup-service' repository"
echo "5. Framework: Next.js (auto-detected)"
echo "6. Root Directory: ./ (default)"
echo "7. Build Command: npm run build"
echo "8. Click 'Deploy'"
echo ""

echo "📋 Step 4: Set Environment Variables in Vercel"
echo "1. Go to your project settings in Vercel"
echo "2. Click 'Environment Variables'"
echo "3. Add these variables:"
echo "   - STRIPE_PUBLISHABLE_KEY=pk_test_..."
echo "   - STRIPE_SECRET_KEY=sk_test_..."
echo "   - NEXT_PUBLIC_SITE_URL=your-domain.vercel.app"
echo ""

echo "📋 Step 5: Configure Stripe"
echo "1. Go to https://stripe.com and create account"
echo "2. Go to Dashboard → Products"
echo "3. Create new product: 'OpenClaw Setup Service'"
echo "4. Price: $50.00 USD"
echo "5. Copy the Price ID to your Vercel env vars"
echo ""

echo "📋 Step 6: Update Payment Integration"
echo "Replace the demo payment form with actual Stripe checkout"
echo "in src/app/purchase/page.tsx"
echo ""

echo "🎯 Step 7: Launch Marketing Campaign"
echo "1. Record demo video (3 minutes)"
echo "2. Schedule social media posts"
echo "3. Send launch email to network"
echo "4. Start day 1 marketing activities"
echo ""

echo "💰 Revenue Goal: $1,000 in Week 1!"
echo "=================================="
echo ""
echo "Your live site will be: https://your-project-name.vercel.app"
echo ""
echo "Ready to make some money! 🚀"